version: 2.1

executors:
  jdk:
    docker:
      - image: openjdk:8-jdk
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

commands:
  with_cache:
    parameters:
      steps:
        type: steps
    steps:
      - restore_cache:
          keys:
            - v3-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}-{{ checksum "buildSrc/src/main/kotlin/Lib.kt" }}
            - v3-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}
            - v3-{{ checksum "build.gradle.kts" }}
            - v3-
      - steps: << parameters.steps >>

jobs:
  test:
    executor: jdk
    steps:
      - checkout
      - with_cache:
          steps:
            - run: ./gradlew dependencies

            - save_cache:
                paths:
                  - ~/.gradle
                  - .gradle
                key: v3-{{ checksum "build.gradle.kts" }}-{{ checksum "buildSrc/src/main/kotlin/Plugin.kt" }}-{{ checksum "buildSrc/src/main/kotlin/Lib.kt" }}

            - run: ./gradlew test
            - store_test_results:
                path: build/test-results

workflows:
  full_workflow:
    jobs:
      - test
